### ISSUE TITLE
When publishing an Android lib to maven, the locked dependencies are not being passed into the generated POM file. The POM contains the '+' instead of the locked versions.

### ISSUE THREAD

**Issue by mr-e-** [nebula-plugins/gradle-dependency-lock-plugin#110]
Not sure if this is a bug or a feature request but I have other teams that pull my libraries from maven, I would like them to be able to pull published libs, libs that may reference other libs with a '+', but when it is published to maven contain a locked version in the POM file so the other teams don't accidentally pull in a new version of a second level dependency without their knowledge. I don't want to force these teams to have to use the plugin as well, I would like them to be able to consume our libraries and get a consistent build, no matter if we publish another version of a second level dependency.

**Comment by rspieldenner** [comment]
The nebula-publishing-plugin does some of that conversion. Dependency lock
has no opinion on publishing currently.

**Comment by mr-e-** [comment]
Can that be used by Android? What do you mean 'some' of that conversion?

Currently we are using:

apply plugin: 'maven'
//noinspection GroovyMissingReturnStatement
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "https://nexus.com:8444/nexus/content/repositories/sa-releases/") {
                authentication(userName: "sareleasedeployment", password: getSAReleaseNexusPassword())
            }
            snapshotRepository(url: "https://nexus.com:8444/nexus/content/repositories/sa-snapshots") {

                authentication(userName: "sadeployment", password: getSANexusPassword())
            }
            pom.groupId = getGroupId()
            pom.version = generateVersion()
            pom.artifactId = getArtifactId()
        }
    }
}

We would need to completely replace this?

**Comment by rspieldenner** [comment]
Nebula publishing uses maven-publish as the basis, you can check the source
to see what we do to convert dynamic dependencies. I do not know if it will
work for your use case. We separate out locking, publishing, and bintray
publishing into separate plugins since they are separate concerns

**Comment by saantiaguilera** [comment]
Im having this exact same issue, what would be the plugin for the conversion ? Or how have other people achieve this ??

**Comment by DanielThomas** [comment]
This is Gradle's default behavior - it publishes the requested version, rather than the resolved version.

The resolved-versions plugins from https://github.com/nebula-plugins/nebula-publishing-plugin will publish resolved, rather than requested versions:

- https://plugins.gradle.org/plugin/nebula.maven-resolved-dependencies
- https://plugins.gradle.org/plugin/nebula.ivy-resolved-dependencies

Otherwise you're left hand crafting something like this:

https://github.com/nebula-plugins/nebula-publishing-plugin/blob/master/src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy
