### ISSUE TITLE
Use version from lockfile when uploading to maven repository

### ISSUE THREAD

**Issue by vbrandl** [nebula-plugins/gradle-dependency-lock-plugin#124]
Currently when you are using the dependency lock plugin and upload the project into a maven repository using the `uploadArchvies` task, the `pom` file still contains the version range.
It would be great if instead the locked version would be written into the `pom` if there is a lock in the project.

**Comment by DanielThomas** [comment]
@vbrandl not really a concern of locks, Gradle always publishes the requested version, rather than the selected version. This plugin will rewrite the pom for you, to ensure that conflict resolution, replacements, substitutions etc are reflected:

https://plugins.gradle.org/plugin/nebula.maven-resolved-dependencies
